# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts&tabs=schema

trigger:
- master

pool:
  vmImage: 'macOS-10.13'

steps:
- task: ShellScript@2
  inputs:
    scriptPath: './build-mac.sh'
    #targetType: 'filePath' # Optional. Options: filePath, inline
    #filePath: # Required when targetType == FilePath
    #arguments: # Optional
    #workingDirectory: # Optional
    #failOnStderr: false # Optional
