# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts&tabs=schema

trigger:
- master

pool:
  vmImage: 'macOS-10.13'

steps:
- task: Bash@3
  inputs:
    #targetType: 'filePath' # Optional. Options: filePath, inline
    #filePath: # Required when targetType == FilePath
    #arguments: # Optional
    script: './build-mac.sh'
    #workingDirectory: # Optional
    #failOnStderr: false # Optional
